# Generated by Django 4.2.13 on 2024-06-22 12:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediaplatform',
            options={'ordering': [django.db.models.functions.text.Upper('name'), 'id'], 'verbose_name': 'digital platform'},
        ),
        migrations.AlterModelOptions(
            name='socialmediapost',
            options={'ordering': ['id'], 'verbose_name': 'post'},
        ),
        migrations.AlterModelOptions(
            name='socialmediapostimage',
            options={'ordering': ['id'], 'verbose_name': 'post image'},
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='content_video_other',
            field=models.CharField(blank=True, help_text='If the video is in a format other than YouTube or Vimeo please include a URL to the video here', max_length=1000, null=True, verbose_name='content video (other)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_media_profiles',
            field=models.TextField(blank=True, help_text='List the URL for each social media profile for this Author on a new line in the text box', null=True, verbose_name='digital profiles'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='social_media_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socialmediaposts', to='researchdata.socialmediaplatform', verbose_name='digital platform'),
        ),
        migrations.CreateModel(
            name='CountryConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description (English)')),
                ('description_es', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description (Spanish)')),
                ('published', models.BooleanField(default=False, help_text='Tick to make available on public website to all users')),
                ('authors', models.ManyToManyField(blank=True, related_name='countryconnections', to='researchdata.author', verbose_name='author(s)')),
                ('country_primary', models.ForeignKey(help_text='Choose the country that appears first alphabetically in the event.', on_delete=django.db.models.deletion.RESTRICT, related_name='countryconnections_primary', to='researchdata.country', verbose_name='Country (primary)')),
                ('country_secondary', models.ForeignKey(help_text='Choose the country that appears last alphabetically in the event.', on_delete=django.db.models.deletion.RESTRICT, related_name='countryconnections_secondary', to='researchdata.country', verbose_name='Country (secondary)')),
                ('posts', models.ManyToManyField(blank=True, related_name='countryconnections', to='researchdata.socialmediapost', verbose_name='post(s)')),
            ],
            options={
                'ordering': ['country_primary', 'country_secondary', django.db.models.functions.text.Upper('title'), 'id'],
            },
        ),
    ]
