# Generated by Django 4.2.6 on 2023-11-06 16:32

from django.db import migrations
import django.db.models.functions.text
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': [django.db.models.functions.text.Upper('name'), 'id'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='content_video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Provide a URL of a video hosted on YouTube/Vimeo, e.g. https://www.youtube.com/watch?v=BHACKCNDMW8', null=True),
        ),
    ]
